# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayImage', models.CharField(blank=True, max_length=2048)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
                ('layer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArmVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to=b'')),
                ('armId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Arm')),
            ],
        ),
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayImage', models.CharField(blank=True, max_length=2048)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
                ('layer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BackVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to=b'')),
                ('armId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Arm')),
                ('backId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Back')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayImage', models.CharField(blank=True, max_length=2048)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
                ('layer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to=b'')),
                ('armId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Arm')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Color')),
                ('legId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Leg')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayImage', models.CharField(blank=True, max_length=2048)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
                ('layer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PipeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to=b'')),
                ('armId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Arm')),
                ('backId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Back')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Color')),
                ('pipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Leg')),
            ],
        ),
        migrations.CreateModel(
            name='SofaKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayImage', models.CharField(blank=True, max_length=2048)),
                ('displayName', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='backvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Color'),
        ),
        migrations.AddField(
            model_name='armvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Color'),
        ),
        migrations.AddField(
            model_name='arm',
            name='kindId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.SofaKind'),
        ),
    ]
