# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csofa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legvariant',
            name='color',
        ),
    ]
