# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csofa', '0002_remove_legvariant_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pipevariant',
            name='pipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csofa.Pipe'),
        ),
    ]
