# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csofa', '0003_auto_20160719_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='diplayImage',
            field=models.FileField(default='null', upload_to=b''),
            preserve_default=False,
        ),
    ]
